language: node_js
node_js:
- '0.12'
- '0.10'
after_success: npm run-script codeclimate
deploy:
  provider: npm
  email: krzysiek@codilogy.com
  api_key:
    secure: Ur4dkzqjKeKWAga+Hi4lpFGG7EMqJ//YXLFAKV0K2syQ8Cr5w9UadDhLjmjujdk8Og7MCroh9YloYdffMDb3DW8WMqen2GvapeEbjglaoLAwFImdkD3ChJWz+GYgMG6ARw5AZo7iEB8CgK7JPtS27pPSvOWv3uoWB1ZEFclEpIU=
  on:
    tags: true
    repo: kwiniarski/http-promise
